name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Test default react-scripts to compare time
  test-react-scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile create-react-app examples using react-scripts
        run: |
          pnpm run build-react-scripts --filter "with-*"

      - name: Test create-react-app examples using react-scripts
        run: |
          pnpm run test-react-scripts --filter "with-*"

  # Test craco without any config to compare time
  test-craco-empty:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile create-react-app examples using craco
        run: |
          pnpm run build --filter "with-*" -- --config ../../config/craco.config.js

      - name: Test create-react-app examples using craco
        run: |
          pnpm run test --filter "with-*" -- --config ../../config/craco.config.js

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Compile create-react-app examples using craco
        run: |
          pnpm run build --filter "with-*"

      - name: Test create-react-app examples using craco
        run: |
          pnpm run test --filter "with-*"
